# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-02 09:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name=datetime.datetime(2018, 4, 2, 9, 5, 3, 529900, tzinfo=utc))),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('date', models.DateField(auto_now=True)),
                ('is_leave', models.BooleanField(default=False)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MajorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('studentNum', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=15)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('hobby', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.IntegerField(default=1)),
                ('phone', models.CharField(max_length=11)),
                ('motto', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('userImg', models.ImageField(null=True, upload_to='')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ClassInfo')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.MajorInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserType'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='studentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo'),
        ),
    ]
