# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-04 09:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='userImg',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='day',
            field=models.DateField(verbose_name=datetime.datetime(2018, 4, 4, 9, 19, 57, 862662, tzinfo=utc)),
        ),
    ]
