# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-08 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180404_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='day',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='start_time',
        ),
        migrations.AddField(
            model_name='attendence',
            name='cur_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendence',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
