# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-08 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180408_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='studentNum',
            new_name='stu',
        ),
    ]
