# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180411_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='cur_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
