# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180411_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='cur_time',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='state',
        ),
        migrations.AddField(
            model_name='attendence',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
