# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-13 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180411_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
