# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_attendence_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
