# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-13 15:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180413_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 4, 13, 15, 24, 36, 34076)),
        ),
    ]
