# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-14 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180413_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('head', models.TextField(max_length=200)),
                ('content', models.TextField(max_length=500)),
                ('level', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 17, 35, 26, 303785)),
        ),
    ]
