# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-14 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180414_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 17, 43, 35, 858786)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
